excerpt_separator: ""
#pygments: true
highlighter: rouge
markdown: kramdown
url: http://efeefe.github.io
title: efeefe
tagline: Blogue do efeefe
description: Anota&ccedil;&otilde;es sobre a vida, o mundo e as coisas.
paginate: 5
